In [3]:
import os
import pandas as pd

In [4]:
data_dir = "../data/raw/physionet.org/files/ptb-xl/1.0.1"
data_path = os.path.join(data_dir, "ptbxl_database.csv")

In [16]:

table = pd.read_csv(data_path, index_col="ecg_id")
technical_features = ["patient_id", "nurse", "device", "recording_date", "report", "scp_codes", "strat_fold", "filename_lr", "filename_hr"]
table = table.drop(columns=technical_features)
table.head()

,age,sex,height,weight,site,heart_axis,infarction_stadium1,infarction_stadium2,validated_by,second_opinion,initial_autogenerated_report,validated_by_human,baseline_drift,static_noise,burst_noise,electrodes_problems,extra_beats,pacemaker
ecg_id,,,,,,,,,,,,,,,,,,
1,56.0,1,NaN,63.0,0.0,NaN,NaN,NaN,NaN,False,False,True,NaN,", I-V1,",NaN,NaN,NaN,NaN
2,19.0,0,NaN,70.0,0.0,NaN,NaN,NaN,NaN,False,False,True,NaN,NaN,NaN,NaN,NaN,NaN
3,37.0,1,NaN,69.0,0.0,NaN,NaN,NaN,NaN,False,False,True,NaN,NaN,NaN,NaN,NaN,NaN
4,24.0,0,NaN,82.0,0.0,NaN,NaN,NaN,NaN,False,False,True,", II,III,AVF",NaN,NaN,NaN,NaN,NaN
5,19.0,1,NaN,70.0,0.0,NaN,NaN,NaN,NaN,False,False,True,", III,AVR,AVF",NaN,NaN,NaN,NaN,NaN

In [30]:
print("Nan count by feature")
table.isna().sum()

Nan count by feature

age                                89
sex                                 0
height                          14854
weight                          12408
site                               18
heart_axis                       8505
infarction_stadium1             16211
infarction_stadium2             21734
validated_by                     9411
second_opinion                      0
initial_autogenerated_report        0
validated_by_human                  0
baseline_drift                  20230
static_noise                    18575
burst_noise                     21224
electrodes_problems             21807
extra_beats                     19883
pacemaker                       21544
dtype: int64

In [29]:
unique_values = {col: (len(table[col].unique()), table[col].dtype) for col in table.columns}
print("UNIQUE VALUES:\n")

for name, (count, dtype) in unique_values.items():
    print(f"{name}: {count} -- {dtype}")

UNIQUE VALUES:

age: 95 -- float64
sex: 2 -- int64
height: 78 -- float64
weight: 128 -- float64
site: 52 -- float64
heart_axis: 9 -- object
infarction_stadium1: 7 -- object
infarction_stadium2: 4 -- object
validated_by: 13 -- float64
second_opinion: 2 -- bool
initial_autogenerated_report: 2 -- bool
validated_by_human: 2 -- bool
baseline_drift: 322 -- object
static_noise: 125 -- object
burst_noise: 104 -- object
electrodes_problems: 15 -- object
extra_beats: 129 -- object
pacemaker: 5 -- object